Add composite propagators
yangxikun/opentelemetry-lua pull request #12
Opened 2022-06-24 21:18 UTC by plantfansam

The OpenTelemetry spec includes [Composite Propagators](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/context/api-propagators.md#composite-propagator), which allow you to run several propagators in sequence. This work adds composite propagators. Along the way, it makes propagators configurable, so that users can decide how their context gets propagated (the spec [requires support for b3, jaeger, and w3c baggage](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/context/api-propagators.md#propagators-distribution)).

In order to add composite propagators, I did a few things:

1. relocated `trace_context.lua` to `text_map/trace_context_propagator.lua`.
1. deleted `carrier.lua`, since the code is not using it anymore
1. updated the method signature of inject and extract to include optional getter/setter arguments (see [spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/context/api-propagators.md#getter-argument)).
1. added modules for composite propagator, getter, and setter.
1. updated nginx.conf in the `examples` directory.

I also added a test harness for [`busted`](https://olivinelabs.com/busted/) tests, along with a `make` command to run them.

These changes will require existing users to modify their code. If that is not acceptable, we can find a solution 😄. 

I'm new to Lua, so I'm sure there are plenty of changes required, but I wanted to get some 👀 .

2022-06-25 12:29 UTC, yangxikun commented
Please rebase main branch.

2022-06-27 15:41 UTC, yangxikun commented
@plantfansam Please check the review.

2022-06-28 04:49 UTC, yangxikun commented
@plantfansam You cannot see this review?

2022-06-28 14:42 UTC, plantfansam commented
@yangxikun I cannot see that review. The comments are shown as pending in the screenshot you posted. I think you need to click "submit review," like this:

<img width="650" alt="Screen Shot 2022-06-28 at 8 41 15 AM" src="https://user-images.githubusercontent.com/370182/176207981-493fe752-0371-4141-bca0-02fc8535c745.png">

2022-06-29 05:03 UTC, yangxikun requested changes

2022-06-29 15:20 UTC, plantfansam commented on lib/opentelemetry/trace/propagation/text_map/composite_propagator.lua
> +function _M:composite_inject(context, carrier)
👍 22b1afdaaf7f875acd0752d3fc4908210d388f1b

2022-06-29 15:34 UTC, plantfansam commented on lib/opentelemetry/trace/id_generator.lua
> +math.randomseed(os.time(os.date("!*t")))
✅  cf0b82cb34b6c85364b4a1f1fc6615c7cc4936ba

2022-06-30 11:20 UTC, yangxikun commented on lib/opentelemetry/trace/propagation/text_map/getter.lua
> +-- Add tracing information to nginx request as headers
wrong doc

2022-06-30 15:04 UTC, yangxikun approved these changes

2022-06-30 15:04 UTC, merged