Pass context not span_context to sampler in tracer
yangxikun/opentelemetry-lua pull request #49
Opened 2022-11-04 20:20 UTC by rdooley

https://github.com/yangxikun/opentelemetry-lua/issues/48

2022-11-04 20:29 UTC, rdooley commented
I will work on adding spec coverage for the other samplers now in a separate commit

2022-11-07 06:28 UTC, yangxikun requested changes

2022-11-07 06:28 UTC, yangxikun commented on lib/opentelemetry/trace/sampling/parent_base_sampler.lua
> +    local parent_ctx = parameters.parent_ctx:span_context()
`parent_ctx` and `parameters.parent_ctx` now have different meaning, `parameters.parent_ctx` should rename to `parameters.context`

2022-11-08 17:25 UTC, rdooley commented
<details>

<summary> oddly working locally </summary>

```
 make openresty-unit-test CONTAINER_ORCHESTRATOR=podman-compose
podman-compose exec  -- openresty bash -c 'cd /opt/opentelemetry-lua && prove -r'
['podman', '--version', '']
using podman version: 4.3.0
podman exec --interactive --tty opentelemetry-lua_openresty_1 bash -c cd /opt/opentelemetry-lua && prove -r
./t/context.t ................................ ok
./t/trace/batch_span_processor.t ............. ok
./t/trace/sampling/parent_base_sampler.t ..... ok
./t/trace/sampling/trace_id_ratio_sampler.t .. ok
./t/trace/span_finish_timestamp.t ............ ok
./t/trace/tracer.t ........................... ok
./t/trace/tracer_provider.t .................. ok
All tests successful.
Files=7, Tests=41, 21 wallclock secs ( 0.02 usr  0.01 sys +  0.45 cusr  0.24 csys =  0.72 CPU)
Result: PASS
exit code: 0
```

</details>

2022-11-08 23:50 UTC, rdooley commented
I mistakenly thought tests were passing due developer error (poor git state locally)
Apologies

2022-11-09 16:28 UTC, yangxikun approved these changes

2022-11-09 16:34 UTC, yangxikun commented
<img width="572" alt="image" src="https://user-images.githubusercontent.com/3364160/200886695-1e7d5e59-4069-4cb5-9692-14d919c771e2.png">

@rdooley These need to fix.

2022-11-14 22:41 UTC, rdooley commented
Finally clicked the button to get [workflows for my fork](https://github.com/rdooley/opentelemetry-lua/actions/runs/3465725167/jobs/5788807806) so now i have some confidence in that, and learned how to replicate this stuff locally which was a little bumpy at times.

Note to others if you see this `cd /opt/opentelemetry-lua && luarocks make && nginx -s reload` on the openresty container

2022-11-15 02:35 UTC, merged